language: python

matrix:
  include:
    - python: 3.6
      dist: xenial
      sudo: true
    - python: 3.7
      dist: xenial
      sudo: true

# command to install dependencies
before_install:
  - sudo apt-get install libhdf5-serial-dev proj-bin libproj-dev libgeos-dev libspatialindex-dev 

install:
  - pip install cython
  - pip install .
  - pip install coveralls

# command to run tests
script:
  - nosetests --with-doctest --with-coverage -c nose.cfg

after_success:
  - coveralls
